<?php
$servername = "localhost";
$username = "f32ee";
$password = "f32ee";

// Create connection
$conn = mysqli_connect($servername, $username, $password);

// Check connection
if (!$conn) {
  die("Connection failed: " . mysqli_connect_error());
}

// TODO: parse prices to int
$lowPrice = $_POST['price_low'] ?: '0';
$highPrice = $_POST['price_high'] ?: '10000000';


$genderGroup = $_POST['gender'];
$categoryGroup = $_POST['category'];

$filterQuery = 'JOIN category ON category.id = product.category_id WHERE price>=' . $lowPrice . ' and price<=' . $highPrice;

if (count($genderGroup) > 0) {
  $filterQuery .= ' and (' . implode(" or ", array_map(function ($gender) {
    return ' gender=' . '"' . $gender . '"';
  }, $genderGroup)) . ')';
}

if (count($categoryGroup) > 0) {
  $filterQuery .= ' and (' . implode(" or ", array_map(function ($category) {
    return ' category.name=' . '"' . $category . '"';
  }, $categoryGroup)) . ' )';
}


/**
 * ### Filter function generated by form submission
 * 
 * @param null
 * @return string[]|string|null|false
 */
function getFilteredProduct()
{
  global $conn, $filterQuery;

  $sql = "SELECT id, name, price, gender, rating, sale_status, category FROM product " . $filterQuery;
  $result = mysqli_query($conn, $sql);

  if (mysqli_num_rows($result) > 0) {
    return mysqli_fetch_assoc($result);
  } else {
    return "0 results";
  }

  mysqli_close($conn);
}