<?php
$servername = "localhost";
$username = "f32ee";
$password = "f32ee";

// Create connection
$conn = mysqli_connect($servername, $username, $password);

// Check connection
if (!$conn) {
  die("Connection failed: " . mysqli_connect_error());
}

/**
 * ### Filter function generated by form submission
 * 
 * @param null
 * @return string[]|string|null|false
 */
function getFilteredProduct()
{
  global $conn;

  $lowPrice = $_POST['price_low'] ?: '0';
  $highPrice = $_POST['price_high'] ?: '10000000';

  $genderGroup = $_POST['gender'];
  $categoryGroup = $_POST['category'];

  $filterQuery = 'JOIN category ON category.id = product.category_id WHERE price>=' . $lowPrice . ' and price<=' . $highPrice;

  if (count($genderGroup) > 0) {
    $filterQuery .= ' and (' . implode(" or ", array_map(function ($gender) {
      return ' gender=' . '"' . $gender . '"';
    }, $genderGroup)) . ')';
  }

  if (count($categoryGroup) > 0) {
    $filterQuery .= ' and (' . implode(" or ", array_map(function ($category) {
      return ' category.name=' . '"' . $category . '"';
    }, $categoryGroup)) . ' )';
  }


  $sql = "SELECT product.id as prod_id, product.name as prod_name, price, gender, rating, sale_status, category.name as cat_name FROM product " . $filterQuery . ";";
  $result = mysqli_query($conn, $sql);

  if (mysqli_num_rows($result) > 0) {
    return $result;
  } else {
    return "0 results";
  }

  mysqli_close($conn);
}